name: peg_insertion_side
num_cameras: 2
cameras:
  - 'front_camera'
  - 'wrist_camera'
shape_meta:
  images: 256
  low_dims: 14
  actions: 7
image_mask_keys:
  - 'front_camera_masks'
  - 'wrist_camera_masks'
env_runner:
  _target_: icon.env_runner.EnvRunner
  env: 
    _target_: icon.envs.maniskill_env.ManiskillEnv
    task: ${task_name}
    cameras: ${task.cameras}
    shape_meta: ${task.shape_meta}
    image_mask_keys: ${task.image_mask_keys}
    robot: "panda"
    control_mode: "pd_joint_pos"
    render_mode: "rgb_array"
    render_size: 512
    obs_mode: "rgb+segmentation"
    
  obs_horizon: ${algo.obs_horizon}
  action_horizon: ${algo.action_horizon}
  max_episode_steps: 100
  num_trials: 50
  initial_seed: 100
  video_save_dir: videos/${task_name}/${algo_name}