train:
  _target_: torch.utils.data.DataLoader
  batch_size: ${train.batch_size}
  shuffle: true
  num_workers: 4
  pin_memory: true

val:
  _target_: torch.utils.data.DataLoader
  batch_size: ${train.batch_size}
  shuffle: false
  num_workers: 4
  pin_memory: true
